name: Deployment workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  
  jobs:
    job_one:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
      - name: Testing firstubuntu via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: 22
          script: |
          cd /home/pascal/ocdap10_pur_beurre
          touch jesuisla.txt
          git pull origin main
          git status